### PR TITLE
Fix Post Excerpt

### PR DESCRIPTION
**Pull request by illusion0001**

### CODE REVIEW

**Review by jeffreytse — COMMENTED** [review]
@illusion0001, thanks for your PR, the excerpt variable is defined here:
https://github.com/jeffreytse/jekyll-theme-yat/blob/5fde56f5d0075a2ee0087df3903bd94535879297/_includes/views/pagination.html#L19-L20

We get the article excerpt from the custom funcition.

**Comment by illusion0001** [comment]
image

**Comment by jeffreytse** [comment]
Yes, this excerpt size can be set from the `config.yml` by the `excerpt_size` option, this is for settling the `CJK` issue and just pure text, so we don't use the `post.excerpt`.

**Comment by illusion0001** [comment]
Ah okay.

**Pull request closed without merging**
