### PR TITLE
feat: re-format copyright message and auto increase copyright end year based on the current year

### PR DESCRIPTION
**Pull request by Anthonyive**
## Simple explanation:

Screen Shot 2021-06-25 at 12 52 02 AM

```yml
copyright: GitHub User
copyright_start_date: 2017
copyright_end_date: 2020
copyright_auto_increase: false 
# if set to true, the copyright end date will be overwritten and auto increased
```

### CODE REVIEW

**Comment by jeffreytse** [comment]
Hi @Anthonyive 

Firstly, thanks for the PR on auto updating the copyright period. For the year of copyright, I don't recommend to use a third-party gem, could you refactor it and implement it by the placeholder parameter?

For example:

```yml
copyright: "(c)copyright 2017-{currentYear}"
```

Thanks and regards

**Review by jeffreytse — COMMENTED** [review]
The implement of auto increasing copyright period on the current year should be better simplified.

**Comment by Anthonyive** [comment]
@Anthonyive I will remove that gem. That gem was not used for the code. It was just for the local server to work properly since I was using ruby 3.0

**Comment by Anthonyive** [comment]
Thanks for the suggestions! I will look into them.

**Comment by Anthonyive** [comment]
New implementation based on [copyright.gov](https://www.copyright.gov/circs/circ03.pdf):

Write `_config.yml` like this:
```yml
copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"
```

- `{currentYear}` will be replaced with current year
- `{author}` will be replaced with `site.author`
- copyright symbol
  - copyright: © - (c)
  - copyleft: (ɔ)
  - sound recording copyright: ℗ - (p)

**Review by jeffreytse — COMMENTED** [review]
Thanks for the work, and this implement almost reaches the goal.

**Pull request merged**
